import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import AppLayout from "@/components/AppLayout"
import clsx from "clsx"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(montserrat.className, "bg-white")}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}
